### ISSUE TITLE
Repeated queries for simple calendar

### ISSUE THREAD

**Issue by brookiel** [bartekgorny/django-schedule#6]
This is related to [issue 29 in thauber's fork](https://github.com/thauber/django-schedule/issues/#issue/29), but I thought I'd post here as that one seems dead, and the code in question is most likely shared between forks.

This app seems to be duplicating queries. I thought it was my usage that was the problem, but even the project_sample code generates 66 queries to display a weekly view of a calendar -- on a week with no events. Using debug_toolbar, I can see queries like

SELECT "schedule_occurrence"."id", "schedule_occurrence"."event_id", "schedule_occurrence"."title", "schedule_occurrence"."description", "schedule_occurrence"."start", "schedule_occurrence"."end", "schedule_occurrence"."cancelled", "schedule_occurrence"."original_start", "schedule_occurrence"."original_end" FROM "schedule_occurrence" WHERE "schedule_occurrence"."event_id" = 1

being run for event_id 1 to 7, and being run 8 times each. 

In answer to the questions for the thauber bug: I'm not using caching, and I'm not using select_related. I'm just running the example project given. The same thing happens for my own project, and I'm just using the template tags as provided.

Is this the expected behaviour?

**Comment by bartekgorny** [comment]
First, there is no such thing as "week with no events"; there can only be a week with or without occurrences. To check if there are any occurrences within the week in question, we need to look up persisted occurrences, so the code is probably looking them up event by event. I don't know right away why there is so many queries - could you please check two things:
- is what you pasted above the complete queries? I'm a bit surprised there is no datetime clause of some sort
- does it cause performance problems? if not, we don't need to bother; if yes, the issue is serious

**Comment by brookiel** [comment]
Sorry about the terminology mix-up. It is a week with no occurrences.

That is one of the complete queries. The where clause stops at the event_id. If you'd like to see all the queries that it runs, I can send you that as well.

This is a problem for us, as we were planning to use this for a site with many users who will be making lots of changes to events all day. Caching wouldn't help in this situation.

To reproduce: clone, go to project_sample, syncdb, run "python manage.py load_sample_data" and "python manage.py load_example_data" and then go to the current week. If you have django-debug-toolbar installed you should see 66 queries.

**Comment by bartekgorny** [comment]
The reason was that database was queried for persisted occurrences for every event and for every slot in day-table - which doesn't make sense since occurrences are already drawn from dbase by the parent Day. Commit fb03f improves the situation by passing occurrence pool and persisted occurrences (same way it is done by other objects, like Year to Month to Day). For me, the number of queries went down from 160 to 25, which is a bit of an improvement. See if it solves your problem; it could probably be further reduced by doing similar things in other places.

**Comment by bartekgorny** [comment]
7cd46 cuts the number of queries further by about half, and this is probably all I can do right now

**Comment by brookiel** [comment]
That's great! I should be able to give it a try tonight or tomorrow night.

**Comment by sontek** [comment]
I just tested and it seems to only generate 4 queries on a week now
